### PR TITLE
Edit level 2

### PR DESCRIPTION
**Pull request by mgeorge1**
-add mountains
-make water more expansive
-change world lighting system to look brighter & more colorful
-started on flowers and butterflies ♥

### CODE REVIEW

**Comment by jeremyc61298** [comment]
This needs to be rebased before I can merge it

**Comment by jeremyc61298** [comment]
Why is there a merge commit? Did you pull master into this branch instead of rebasing?

**Comment by mgeorge1** [comment]
I’m really not sure what happened.  I did a rebase and even after it was
finished it was saying that there were changes on the master that I didn't
have and it wouldn't allow me to pull those changes without a merge. I'm
working on fixing it right now.

**Comment by jeremyc61298** [comment]
You need to make sure master is checked out when you pull master. If you try to pull master while your branch is checked out, it will merge the code. After you pull master, you then need to checkout your branch again and use `git rebase master` to actually rebase. At this point though, you will likely have other problems

**Comment by mgeorge1** [comment]
Yeah I didn't pull master or anything.  I messed up and was using the wrong
folder so I accidentally merged when it wasn't necessary but it was pretty
much the same file.  I think it's rebased correctly but I'll check it.
It's not giving me any issues now, but I'm hoping it gives nobody else
issues either.

**Comment by jeremyc61298** [comment]
I'm still seeing issues here

**Comment by mgeorge1** [comment]
Working on it.  I'm having to do the rebase over again.

**Comment by mgeorge1** [comment]
I think it's ready

**Pull request merged**
